### ISSUE TITLE
BlurView in background disables Buttons

### ISSUE THREAD

**Issue by nidegen** [danielsaidi/SwiftUIKit#1]
It seems that 

```
ZStack {
  BlurView()
  Button()
}
```
makes Button not to work. Could it have sth to do with the implementation?

**Comment by danielsaidi** [comment]
Oh, good catch! I'll have a look 👍

**Comment by nidegen** [comment]
Seems not to be generally reproducible. Maybe its only when presented above a UIViewRepresentable.. Ill get back if I can isolate it

**Comment by nidegen** [comment]
here we go: the [example code](https://github.com/nidegen/Sketcher/blob/master/Source/LeftTab.swift) can toggle on an off the blur view, which enables or disables buttons. funnily, it works when the blur is not behind any spacers or Images in buttons

**Comment by danielsaidi** [comment]
Great, thanks! I will check and see if the blur does something unexpected with the view hierarchy. Or do you think it's a SwiftUI thing?

**Comment by nidegen** [comment]
Its inconsistent appearance hints to SwiftUI, but it never occurs when I use a Color view instead of BlurView for instance.

I have to admit that I do not expect it to be an easy fix.

Maybe it's the reason why there is no builtin blur in SwiftUI yet 😅

**Comment by nidegen** [comment]
OK, setting `BlurView(style: .systemChromeMaterial).allowsHitTesting(false)` helps. At least sometimes 😅🙈

**Comment by danielsaidi** [comment]
Omg...

**Comment by nidegen** [comment]
I have only been testing in v, h, and zstacks

**Comment by danielsaidi** [comment]
I should probably deprecate the blur view, since we now have native SwiftUI materials instead. What do you think @nidegen ?

**Comment by nidegen** [comment]
Sure! I was using a code copy anyways and I think I switched to the native one now.
