### ISSUE TITLE
Can Build on Xcode 14

### ISSUE THREAD

**Issue by imperio001** [danielsaidi/SwiftUIKit#12]
Hi 
Im getting this error on recent update Xcode 14 and IOS 16 
SwiftUIKit/views/ContactPicker.swift:73:24: error build: Inheritance from non-protocol, non-class type 'ContactPicker.Coordinator' (aka 'any Coordinator')
![Screen Shot 2022-09-14 at 10 13 58 p m](https://user-images.githubusercontent.com/24402931/190305426-f670cbb6-11fb-4083-8f79-ef495f4e2668.png)

**Comment by danielsaidi** [comment]
Hi @imperio001 

That's strange - there is no such view in SwiftUIKit.

Are you perhaps using another library with the same name?

**Comment by imperio001** [comment]
![Screen Shot 2022-09-16 at 12 54 55 p m](https://user-images.githubusercontent.com/24402931/190702308-e4f7d304-5cc0-46fe-9e84-51eb4b9342ef.png)

Hello in this image show the location, show I delete?

**Comment by imperio001** [comment]
thank you int working
