### ISSUE TITLE
Demo run failure

### ISSUE THREAD

**Issue by Lucaziki** [danielsaidi/SwiftUIKit#14]
I've got a weird issue that code run failure. I just download the code and run.
![WX20221128-230503](https://user-images.githubusercontent.com/10707157/204312119-3246a9ee-9d8d-4f93-87b5-d1a06107186a.png)
![WX20221128-230523](https://user-images.githubusercontent.com/10707157/204312196-5c6347f5-c5ff-4a1b-8581-c7f3f8840858.png)
![WX20221128-230603](https://user-images.githubusercontent.com/10707157/204312238-0b7a1130-e52e-48da-9d1f-83b172fb573f.png)
![WX20221128-231050@2x](https://user-images.githubusercontent.com/10707157/204312423-e5c868d3-2b5e-4b93-8386-efdd3aef8bb0.png)

**Comment by danielsaidi** [comment]
Hi @Lucaziki 

Oooops, I had forgotten to push the demo changes.

Thanks for letting me know, it's fixed now! 🙏
