### ISSUE TITLE
ScrollViewGestureButton remains pressed on fast swipe outside the ScrollView

### ISSUE THREAD

**Issue by vszakd** [danielsaidi/SwiftUIKit#25]
Hello, 
when using the ScrollViewGestureButton preview, a combination of touch and swipe can make the button permanently pressed, even if no button should ever remain pressed without an active touch.
No presses on other views will release the button apart from a press on the button itself. 
Even if the button gets eventually released, the repeating action continues to fire. 
Only a long press on the button prevents the repeating action from firing.

See video attached: https://github.com/danielsaidi/SwiftUIKit/assets/8497370/2b0655e8-f2f4-41bf-b305-2b4622f16816.

**Comment by danielsaidi** [comment]
Hi @vszakd 

Thank you, that's a great find! Any idea on how to fix it? :)

**Comment by danielsaidi** [comment]
Thank you so much @vszakd 🙏

**Comment by danielsaidi** [comment]
Thank you for letting me know!
