### ISSUE TITLE
Handle Objective-C exceptions

### ISSUE THREAD

**Issue by stateman92** [danielsaidi/SwiftUIKit#26]
In this line you stated that there might be an exception, but no one handles that:
https://github.com/danielsaidi/SwiftUIKit/blob/08bfed591c0fbec670542098a659aa59f5668481/Sources/SwiftUIKit/Colors/Color%2BCodable.swift#L81

However, with [this library](https://github.com/sindresorhus/ExceptionCatcher) you can catch those exceptions. Or you can even copy that code to this project to avoid using libraries.

**Comment by danielsaidi** [comment]
Hi @stateman92 

That's great, thanks for sharing!

However, I pulled that extension in from another place (see header) and that comment is theirs. I don't think I want to add that extra complexity for something that so far hasn't happened to me :)

But thanks again for the link! 👍
