### ISSUE TITLE
ScrollViewGestureButton issues with iOS18

### ISSUE THREAD

**Issue by jhull** [danielsaidi/SwiftUIKit#30]
Discovered this package recently - wonderful, thank you!

ScrollViewGestureButton was working great for me in iOS17.5, but after upgrading to 18 both on device and in Xcode, I lose all scroll abilities and the view locks up.

This happens in both the simulator and on device.

Relatively new to SwiftUI so not sure how to fix...

**Comment by danielsaidi** [comment]
Hi @jhull 

Thank you for letting me know!

I will extract the buttons to a separate package and have a look at it closer to the iOS 18 release.

**Comment by danielsaidi** [comment]
Hi again @jhull 

I have confirmed the bug and will try to fix what's happening. Did you find any workaround?

**Comment by danielsaidi** [comment]
Hi again @jhull 

I am struggling to fix this issue, which is caused by iOS 18 changing how drag gestures affect scrollviews.

I found more information here:

https://stackoverflow.com/questions/78912852/adding-a-high-priority-drag-gesture-to-a-scrollable-view-in-ios-18-causes-the-sc

**Comment by danielsaidi** [comment]
This component is now available as a separate package:

https://github.com/danielsaidi/GestureButton
