### ISSUE TITLE
I can't build the demo project

### ISSUE THREAD

**Issue by jfrodden** [danielsaidi/SwiftUIKit#5]
I downloaded and tried to build the demo project, but it isn't building and I think this is why:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/45771753/113641014-b8f8ee00-964a-11eb-9174-a0209ff64bf6.png">

**Comment by danielsaidi** [comment]
Thank you, I forgot to change this :) I will fix this within a few hours.

**Comment by danielsaidi** [comment]
@jfrodden Thank you for noticing this! 

I moved these files when I rewrote the list api:s and forgot to update the demo. The `master` branch now pulls SwiftUIKit in via SPM, so this won't happen again :)
