### ISSUE TITLE
OnTapGesutre on CollectionView prevents scrolling

### ISSUE THREAD

**Issue by jlcanale** [danielsaidi/SwiftUIKit#6]
Whenever I add a .OnTapGesture to a view contained in a CollectionView row, the gesture works just fine, but the collection view no longer responds to scrolling.

Is this a bug, or am I just missing something?

**Comment by danielsaidi** [comment]
Hmmm, I must give this a try. I don't have this problem in my tvOS app, which is the only place where I use it.

**Comment by jlcanale** [comment]
Hmm, seems like you're right.  I just tried modifying the CollectionViewShelvesScreen in the Demo app, where I added an .OnTapGesture {} to the view created in the cell(at:for), and it worked just fine.  I must be doing something wrong in my app.  I'll close this issue, but if I solve it, I'll make sure to come back and put notes here as to what I was doing wrong.  Maybe it'll help someone else.

**Comment by danielsaidi** [comment]
Ok, I hope you find the problem! Sharing any findings would be awesome, thank you!
